# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171027_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodSlug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
