# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20171031_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodSlug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
