# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20171201_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catSlug',
            field=models.SlugField(blank=True, max_length=128, unique=True),
        ),
    ]
